language: node_js
node_js:
- 13
services:
- docker
install:
- echo "nothing needs to be installed"
before_script:
- echo "no tests"
script:
- "./build/build.sh"
after_success:
- "./build/upload_images.sh"
env:
  global:
  - DOCKERHUB_USERNAME=tiochan
  - secure: RZgPQeTDRZ2LgqxxSgyzeQ0nRoRPo1R5mFemco3L6Im/qKeoZYas0giwa7CZpCO3hlewWjq3AOS1rIxfwSUzY4C0sIRCZBQ2TdwGONx33FMdSSjeFgfgRxpi5gcewGjBitYjdRl2PIeyHHPELdiaDmrtHQe5/zNCCOq+Zrgvt7Kbp/wM0+oqoAYKTzQNQYE7Y09FdaX6HvqTSb2PqPaaQ0xg3fPesRpws9qaqH0eKHl8DIuhS/lgZeqXzmOQ5mzESg+TQCvbP8GNDxwxaIvrquGINDVpq+ON1scMIxOF7XtWMkt1hLVMoUvf65TShJ6Okl9GHSHRXIE0MbQFWRV7l+iGDGTQ0/TES2qY7Cwpsp8pqVwqKHysUY2OF4pvH2Mn6PyVrO27lNzg8XUsanSbSWj/wzNM0gfouk0lR2kyqbJEz2HoGgRyqkmS3ZvOTMF3EEB5KdaEXNpCZmEP7y/hMCaj13Qn0QtsQc9+YtDlxWKfnG/0DWFkWKB/PFD1MiE07jpAgeJ2gLTaF3gSsiq5xGKnloFjAxKPz7Da6kqMJbSD+wGAl/wIRe8BS+5PEAbWi++VH29YuPI3uYoFZnGQZZDOQmc87zLaajTr1wYYyCxkD3jzSREq6o/FTgSWGQC3kl/u0SciE765y76oaD4v8rX95k7xemEfMp7bv893P+g=
  - secure: NUmlZI3k4tw7r8N1aRoDMAsFZoTnqoFc5XclOOJfweqTChQ+xPuxRBFLdbRm++qFsrHV3O16hOnFzTellfCS2Qc1nvpTU/c8Id5ZtICPXJjwXSG2g19ljw0Vp7GyipCoT6+SMAHTY1EPT11eA3H+Gm/j3waK96WlCXHv+UCfEPTFjz2Tlv4J4aQ/mvIVFJR57aTO12pK8pUfUzU++xB7jiY4UUWZJPeTUNzvJzYLnaOcUsPLpbh/ktl6ku3NBvA5KzhXRD6qEAY5bwOtrcEjFtxqii69r6SlXtaMQqnjIqSutorVAZlC7ZYcr1XAdiwQkeyozEGPBvfKzwnuz+gEhjeXjf2k9TgBtF5cktGS/ijZOo3FABjxqKYq9lQkXbWMtUWlDWdi3ojULd9xQodGn0deas1ZjAsMOReoma3hJMsAA+xSKqfUW0y7MltkWXE4n3lHnF739EZ29HqVE61pdawt1RFWQTJzEWeDnOY0zSUranoUjOUfeBOyOc9nHbam78CSpujj9tAeXSoZVXJtFpIWZ3YB1Ls3ZKP9EkdlYO2GY4ykzPhwEBRHhnQrOjmICHLpCEnK7JMQg+LSIsur4u/YRa75tfw0kP/ZFAvjM1DZM6rVZoaB41L0hWPetdCpnnqDc8+bX5lBO90bH1VXtqnNvklD09sVKy9ubCv/kYo=
  secure: jB+jvhtz7qjM5zDQFcZJ+MAqW6u201Q1lYU1zZH0BuoYcygV8LqhA7l9ZNr4IzX3hlLv9QTxrk4uyHBMtvJjfK3pisLG3BOQdS3jiLW0GgW1NPoLssMIjZlMXtpIaqt3WGSSU3CopFpwMgsvTkDGmZzzPuhzih1Q2kkmYKWwLlICnspLGAMzxq9v2eYq8LYmxZJSAJ5Y0Gym0cQeyilLMD/0mkk5vUB5lcJdU9c6sBNmVor8s1Qj9LnquvIpeHfEGvoxW7AftEbI9qoDwejTn6nie/nsVa8o7E8P87H1g32w5rkL/hQJjc5k70ShA098cznPSjMenBvb1w9g5RnLJImj6zIlQJobnWKZd/x28pRnt5eIxxYY2RmFeK3Qq7aTX/gIgEic2ygmLsPouhSW7z2HFBWa22cbHshGUtvOF+iusw5Xg05giDnk4TL+F3ghYlLWuqel2uJ6E8hPUldBNGqE46b8KvMhqRMBR2vnBh+NGt4VI3KdNX/sZflwyvc4U2KnU819jgYhIpDnOd3uvHWBNFoItZnAlfgaW0kkA90WtSD0t9f7SboqTl3GLUUY3cyFT0wAASnCe1OaLwpkHr1xNojl/j1y1D+pCnXQtXWhbOvW9L+Efl9zA+1DpeHtvezPImXdSAr6HDGEb1O6X+JD1pmN7WD+Ye2mi3pQjws=
