apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - name: frontend
          image: 'tiochan/udagram-frontend:v3'
          resources:
            requests:
              memory: 600Mi
              cpu: 250m
            limits:
              memory: 1500Mi
              cpu: 500m
#          ports:
#          - containerPort: 8080
          envFrom:
            - configMapRef:
                name: udagram-env-vars
                optional: False
